/**
 * The control panel's container, network and door (D63), made and checked by
 * `allvibe panel install` (which install.sh runs) and by the engine at every
 * start (so a new home-network address is picked up).
 *
 *   - its image, built here from the pinned Node.js 24 image and the bundle's
 *     panel/, never pulled;
 *   - its network, Docker `--internal`, with no route out, on the last /24 of
 *     Docker's first address pool, where the panel has a fixed address;
 *   - its container, as the panel's own user, read-only, with no capabilities,
 *     and only the engine's socket folder mounted, read-only;
 *   - its door, one more server of the proxy: the machine's home-network
 *     address, port 8099, private sources only, its own host names only.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { posix as path } from "node:path";
import { BRAND, INSTALL_ROOT, NAMES } from "./brand.js";
import { containerState, docker, engineInfo, tryDocker, waitHealthy } from "./docker.js";
import { lanAddress } from "./project.js";
import { reloadProxy, writeServerConf } from "./proxy.js";
import { tryRun } from "./run.js";

const C = NAMES.command;
export const PANEL_PORT = 8099;
/** Where the panel listens inside its container. */
export const PANEL_INNER_PORT = 8080;
const panelDir = () => path.join(INSTALL_ROOT.split("\\").join("/"), "panel");

/** Every file of the bundle's panel/, in order: what the image is built from. */
function panelFiles(dir = panelDir(), sub = ""): string[] {
  return readdirSync(path.join(dir, sub))
    .sort()
    .flatMap((name) => (statSync(path.join(dir, sub, name)).isDirectory() ? panelFiles(dir, path.join(sub, name)) : [path.join(sub, name)]));
}

export function panelImageTag(dir = panelDir()): string {
  const hash = createHash("sha256");
  for (const file of panelFiles(dir)) hash.update(file).update(readFileSync(path.join(dir, file)));
  return `${C}-panel:${hash.digest("hex").slice(0, 12)}`;
}

/** The last /24 of an address pool: the /24 whose third number is the pool's highest. */
export function lastSubnet(pool: string): string {
  const [base, bits] = pool.split("/");
  const n = base.split(".").reduce((a, o) => a * 256 + Number(o), 0);
  const last = n + 2 ** (32 - Number(bits)) - 256;
  return `${[24, 16, 8, 0].map((s) => Math.floor(last / 2 ** s) % 256).join(".")}/24`;
}

export const panelAddresses = (subnet: string) => {
  const prefix = subnet.split("/")[0].split(".").slice(0, 3).join(".");
  return { gateway: `${prefix}.1`, panel: `${prefix}.2` };
};

/** The panel's door, in the proxy (D63). */
export function panelDoorConf(address: string, panelIp: string): string {
  return `# The control panel's door (D63). Generated by ${C}; rewritten on every change.
server {
    # The machine's home-network address only, IPv4, and private sources only.
    listen ${address}:${PANEL_PORT};
    allow 127.0.0.0/8;
    allow 10.0.0.0/8;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    deny all;

    # Its own names only: a page that points a name of its own at this
    # machine (DNS rebinding) reaches nothing.
    set $panel_host 0;
    if ($host = "${address}") { set $panel_host 1; }
    if ($host = "localhost") { set $panel_host 1; }
    if ($host = "127.0.0.1") { set $panel_host 1; }
    if ($panel_host = 0) { return 421; }

    client_max_body_size 64k;
    location / {
        proxy_pass http://${panelIp}:${PANEL_INNER_PORT};
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_read_timeout 60s;
    }
}
`;
}

function idOf(user: string): { uid: number; gid: number } {
  const entry = tryRun("getent", ["passwd", user]).stdout.split(":");
  if (entry.length < 4) throw new Error(`there is no user ${user}: run install.sh again`);
  return { uid: Number(entry[2]), gid: Number(entry[3]) };
}

export function panelRunArgs(image: string, ip: string, uid: number, gid: number): string[] {
  return [
    "run", "-d",
    "--name", NAMES.panelContainer,
    "--label", `${C}.role=panel`,
    "--network", NAMES.panelNetwork,
    "--ip", ip,
    "--user", `${uid}:${gid}`,
    "--read-only", "--tmpfs", "/tmp:size=8m",
    "--cap-drop", "ALL", "--security-opt", "no-new-privileges:true",
    "--memory", "128m", "--memory-swap", "128m", "--pids-limit", "64",
    "--restart", "unless-stopped",
    "--log-driver", "local", "--log-opt", "max-size=1m",
    // The one mount: the engine's socket folder, which holds nothing else (rule 12).
    "--mount", `type=bind,source=${NAMES.engineDir},target=/run/engine,readonly`,
    "-e", "ENGINE_SOCKET=/run/engine/engine.sock",
    "-e", `PANEL_COOKIE=${C}_panel`,
    "-e", `PANEL_PRODUCT=${BRAND.product}`,
    "-e", `PANEL_COMMAND=${C}`,
    image,
  ];
}

const argsLabel = (args: string[]) => createHash("sha256").update(args.join("\u0000")).digest("hex").slice(0, 12);

export interface PanelChange {
  what: string;
  changed: boolean;
}

/** The image, the network, the container and the door, made what they should be. */
export async function ensurePanel(): Promise<PanelChange[]> {
  const out: PanelChange[] = [];

  const tag = panelImageTag();
  if (tryDocker(["image", "inspect", tag]).code !== 0) {
    docker(["build", "-q", "-t", tag, "--label", `${C}.role=panel-image`, panelDir()], { timeoutMs: 10 * 60_000 });
    out.push({ what: `image ${tag}, built here from the pinned Node.js 24 image`, changed: true });
  } else out.push({ what: `image ${tag}`, changed: false });

  const pools = engineInfo()?.addressPools ?? [];
  if (!pools.length) throw new Error("Docker has no address pools set for the suite's networks: run install.sh again");
  const subnet = lastSubnet(pools[0]);
  const { gateway, panel } = panelAddresses(subnet);
  const existing = tryDocker(["network", "inspect", NAMES.panelNetwork, "--format", "{{.Internal}} {{range .IPAM.Config}}{{.Subnet}}{{end}}"]);
  if (existing.code !== 0) {
    const clash = tryDocker(["network", "ls", "-q"]).stdout.split("\n").filter(Boolean)
      .map((id) => tryDocker(["network", "inspect", id, "--format", "{{.Name}} {{range .IPAM.Config}}{{.Subnet}} {{end}}"]).stdout.trim())
      .find((line) => line.split(" ").slice(1).includes(subnet));
    if (clash) throw new Error(`the panel's network would be ${subnet}, which the network ${clash.split(" ")[0]} already uses`);
    docker(["network", "create", "--internal", "--subnet", subnet, "--gateway", gateway, "--label", `${C}.role=panel`, NAMES.panelNetwork]);
    out.push({ what: `network ${NAMES.panelNetwork}, internal: no route out (${subnet})`, changed: true });
  } else if (existing.stdout.trim() !== `true ${subnet}`) {
    throw new Error(`the network ${NAMES.panelNetwork} is not the panel's (${existing.stdout.trim()}): remove it, and run install.sh again`);
  } else out.push({ what: `network ${NAMES.panelNetwork}, internal`, changed: false });

  const { uid, gid } = idOf(NAMES.panelUser);
  const args = panelRunArgs(tag, panel, uid, gid);
  const want = argsLabel(args);
  const state = containerState(NAMES.panelContainer);
  if (!state.exists || state.labels[`${C}.panel-args`] !== want || state.status !== "running") {
    tryDocker(["rm", "-f", NAMES.panelContainer]);
    const [run, detached, ...rest] = args;
    docker([run, detached, "--label", `${C}.panel-args=${want}`, ...rest]);
    const started = await waitHealthy(NAMES.panelContainer, 60_000);
    if (started.status !== "running" || started.health !== "healthy") throw new Error(`the panel's container is ${started.status}/${started.health}: docker logs ${NAMES.panelContainer} says why`);
    out.push({ what: `container ${NAMES.panelContainer}, as ${NAMES.panelUser}, read-only, with only the engine's socket`, changed: true });
  } else out.push({ what: `container ${NAMES.panelContainer} running`, changed: false });

  out.push(ensurePanelDoor(panel));
  return out;
}

/** The door, for the machine's address now; the proxy reloaded if it changed. */
export function ensurePanelDoor(panelIp?: string): PanelChange {
  const ip = panelIp ?? tryDocker(["inspect", "-f", `{{(index .NetworkSettings.Networks "${NAMES.panelNetwork}").IPAddress}}`, NAMES.panelContainer]).stdout.trim();
  if (!ip) throw new Error(`the panel's container ${NAMES.panelContainer} is not on its network`);
  const address = lanAddress();
  const changed = writeServerConf("panel", panelDoorConf(address, ip));
  if (changed) reloadProxy();
  return { what: `door http://${address}:${PANEL_PORT}/, for private addresses only`, changed };
}

export const panelUrl = () => `http://${lanAddress()}:${PANEL_PORT}/`;
