/**
 * The reverse proxy (D12): one nginx for the whole host, generated here.
 *
 * It runs on the **host's network**, so it sees each visitor's real address and
 * can refuse dev networks at prod's door (rule 1, item 5), and it reaches each
 * environment's app on a port the app publishes to the host's loopback only.
 * Nothing else on the host publishes anything.
 */
import { existsSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { posix as path } from "node:path";
import { NAMES } from "./brand.js";
import { statusPort, type HostConfig } from "./config.js";
import { composeUp, containerState, docker, tryDocker, waitHealthy } from "./docker.js";
import { ensureFile } from "./files.js";

/** nginx, unprivileged, pinned by index digest (like every image the suite pulls). */
export const PROXY_IMAGE =
  "nginxinc/nginx-unprivileged:1.30.5-alpine@sha256:4714e0b1b2577eaa1a6131d07c958b67f0eb68e6d0521e90c6e5287db8cf0bc5";

const dir = NAMES.proxyDir;
const confDir = path.join(dir, "conf.d");
const composeFile = path.join(dir, "compose.json");

export function nginxMainConf(): string {
  return `# Generated by ${NAMES.command}. Do not edit: it is rewritten on every change.
worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    include      /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;
    access_log   off;

    client_max_body_size 25m;
    proxy_http_version   1.1;
    proxy_read_timeout   60s;

    # WebSockets pass through, for apps that use them.
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ""      close;
    }

    include /etc/nginx/conf.d/*.conf;
}
`;
}

export function statusConf(config: HostConfig): string {
  return `# The proxy's own health endpoint, on loopback only.
server {
    listen 127.0.0.1:${statusPort(config)};
    location = /healthz {
        return 200 "ok\\n";
    }
    location / {
        return 404;
    }
}
`;
}

export function proxyCompose(config: HostConfig): string {
  const compose = {
    name: NAMES.proxyProject,
    services: {
      proxy: {
        image: PROXY_IMAGE,
        container_name: NAMES.proxyContainer,
        network_mode: "host",
        restart: "unless-stopped",
        read_only: true,
        tmpfs: ["/tmp:size=16m"],
        cap_drop: ["ALL"],
        security_opt: ["no-new-privileges:true"],
        // nginx directly: the image's entrypoint scripts rewrite files that
        // are read-only here.
        entrypoint: ["nginx"],
        command: ["-g", "daemon off;"],
        volumes: [`${path.join(dir, "nginx.conf")}:/etc/nginx/nginx.conf:ro`, `${confDir}:/etc/nginx/conf.d:ro`],
        healthcheck: {
          test: ["CMD", "wget", "-q", "--spider", `http://127.0.0.1:${statusPort(config)}/healthz`],
          interval: "10s",
          timeout: "3s",
          retries: 3,
          start_period: "5s",
        },
        labels: { [`${NAMES.label}.role`]: "proxy" },
        logging: { driver: "local", options: { "max-size": "10m", "max-file": "3" } },
      },
    },
  };
  return `${JSON.stringify(compose, null, 2)}\n`;
}

/** Test the configuration inside the running proxy, then reload it. */
export function reloadProxy(): void {
  const test = tryDocker(["exec", NAMES.proxyContainer, "nginx", "-t"]);
  if (test.code !== 0) throw new Error(`the proxy's configuration does not pass nginx -t: ${test.stderr.trim().split("\n").slice(-3).join(" ")}`);
  docker(["exec", NAMES.proxyContainer, "nginx", "-s", "reload"]);
}

/** Make the proxy's files and container what they should be. */
export async function ensureProxy(config: HostConfig): Promise<{ changed: boolean; evidence: string }> {
  mkdirSync(confDir, { recursive: true, mode: 0o755 });
  const files = [
    ensureFile(path.join(dir, "nginx.conf"), nginxMainConf()),
    ensureFile(path.join(confDir, "00-status.conf"), statusConf(config)),
  ];
  const composeChanged = ensureFile(composeFile, proxyCompose(config));
  const filesChanged = files.some(Boolean);

  const before = containerState(NAMES.proxyContainer);
  let started = false;
  if (composeChanged || before.status !== "running") {
    composeUp(NAMES.proxyProject, composeFile);
    started = true;
  } else if (filesChanged) {
    reloadProxy();
  }

  const state = await waitHealthy(NAMES.proxyContainer, 60_000);
  if (state.status !== "running" || state.health !== "healthy") {
    throw new Error(`the proxy container is ${state.status}/${state.health}`);
  }
  const changed = composeChanged || filesChanged || started;
  return { changed, evidence: `proxy ${NAMES.proxyContainer} running and healthy${started ? " (started)" : filesChanged ? " (reloaded)" : ""}` };
}

/** One project environment's server block. */
export function writeServerConf(name: string, content: string): boolean {
  return ensureFile(path.join(confDir, `${name}.conf`), content);
}

export function removeServerConf(name: string): boolean {
  const file = path.join(confDir, `${name}.conf`);
  if (!existsSync(file)) return false;
  rmSync(file);
  return true;
}

export function serverConfs(): string[] {
  try {
    return readdirSync(confDir).filter((f) => f.endsWith(".conf") && f !== "00-status.conf");
  } catch {
    return [];
  }
}
